<a href="https://colab.research.google.com/github/MaddoSaru/machinelearning-az/blob/master/Tarea%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Tarea 1***

# **Procesamiento de datos**

**Importar librerías**

In [68]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importar el dataset**

In [69]:
dataset = pd.read_csv("https://raw.githubusercontent.com/MaddoSaru/machinelearning-az/master/datasets/Part%207%20-%20Natural%20Language%20Processing/Section%2036%20-%20Natural%20Language%20Processing/Restaurant_Reviews.tsv", delimiter = "\t", quoting = 3)

**Limpieza de texto**

In [70]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


**Crear Bag of Words**

In [71]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values

**Dividir el dataset en Entrenamiento y Testing**

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# **Procesamiento de Lenguajes Naturales**

**Ajustar el clasificador en el conjunto de Entrenamiento**

In [37]:
from sklearn.naive_bayes import GaussianNB
classifier_LN = GaussianNB()
classifier_LN.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

**Predicción con el conjunto de Testing**

In [38]:
y_pred  = classifier_LN.predict(X_test)
print(y_pred)

[1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1
 0 1 1 1 1 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1
 0 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0
 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 0 1 1
 1 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0
 1 0 1 0 1 1 0 1 1 1 0 1 1 1 1]


**Matriz de Confusión**

In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[55 42]
 [12 91]]


# **Naïve Bayes**

**Ajuste del modelo**

In [77]:
from sklearn.naive_bayes import GaussianNB
classifier_NB = GaussianNB()
classifier_NB.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

**Predicción con el conjunto de Testing**

In [78]:
y_pred  = classifier.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1 0 0
 0 0 1 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0
 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0]


**Matriz de confusión**

In [79]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[87 10]
 [46 57]]


**Resultados**

In [80]:
TN=cm[1,1]
TP=cm[0,0]
FN=cm[1,0]
FP=cm[0,1]
ACC=(TP+TN)/(TP+TN+FP+FN)
PCS=(TP)/(TP+FP)
RCL=(TP)/(TP+FN)
print("Accuracy: ",ACC)
print("Precisión: ",PCS)
print("Recall: ",RCL)
print("F1 Score: ",2*PCS*RCL/(PCS+RCL))

Accuracy:  0.72
Precisión:  0.8969072164948454
Recall:  0.6541353383458647
F1 Score:  0.7565217391304349


# **Support Vector Machine (SVM)**

**Ajuste del modelo**

In [81]:
from sklearn.svm import SVC
classifier = SVC(kernel = "linear", random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

**Predicción con el conjunto de Testing**

In [82]:
y_pred = classifier.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0
 0 0 1 1 1 1 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0
 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0
 1 0 1 0 0 1 1 1 1 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0
 0 1 0 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 1 0 1 1 0 1]


**Matriz de confusión**

In [83]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[74 23]
 [33 70]]


**Resultados**

In [84]:
TN=cm[1,1]
TP=cm[0,0]
FN=cm[1,0]
FP=cm[0,1]
ACC=(TP+TN)/(TP+TN+FP+FN)
PCS=(TP)/(TP+FP)
RCL=(TP)/(TP+FN)
print("Accuracy: ",ACC)
print("Precisión: ",PCS)
print("Recall: ",RCL)
print("F1 Score: ",2*PCS*RCL/(PCS+RCL))

Accuracy:  0.72
Precisión:  0.7628865979381443
Recall:  0.6915887850467289
F1 Score:  0.7254901960784315


# **Random Forest**

**Ajuste del modelo**

In [85]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = "entropy", random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

**Predicción con el conjunto de Testing**

In [86]:
y_pred = classifier.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1 0 0
 0 0 1 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0
 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0]


**Matriz de confusión**

In [87]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[87 10]
 [46 57]]


**Resultados**

In [88]:
TN=cm[1,1]
TP=cm[0,0]
FN=cm[1,0]
FP=cm[0,1]
ACC=(TP+TN)/(TP+TN+FP+FN)
PCS=(TP)/(TP+FP)
RCL=(TP)/(TP+FN)
print("Accuracy: ",ACC)
print("Precisión: ",PCS)
print("Recall: ",RCL)
print("F1 Score: ",2*PCS*RCL/(PCS+RCL))

Accuracy:  0.72
Precisión:  0.8969072164948454
Recall:  0.6541353383458647
F1 Score:  0.7565217391304349
